"""empty message

Revision ID: 9eebd4475a00
Revises: a11d0f25b6c3
Create Date: 2018-05-05 20:28:24.651295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9eebd4475a00'
down_revision = 'a11d0f25b6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription_item', sa.Column('drug', sa.String(length=60), nullable=True))
    op.drop_column('prescription_item', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription_item', sa.Column('name', mysql.VARCHAR(length=60), nullable=True))
    op.drop_column('prescription_item', 'drug')
    # ### end Alembic commands ###
